# Generated by Django 4.2 on 2024-03-16 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='property',
            new_name='Asset',
        ),
    ]
